spring:
  profiles:
    active:
      - test

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false


  mail:
    host: smtp.gmail.com
    username: 
    password: 
    properties:
      smtp:
        auth: true
        socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory
          fallback: false
        starttls:
          enable: true
        ssl:
          enable: true

jwt:
  secret: SequenciaDeCaracteresParaAssinarToken
  expiration: 60000

mail:
  default:
    sender: fabio.hb@gmail.com
    recipient: fabio.hb@gmail.com
  