spring:
  profiles:
    active:
      - test

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false


  mail:
    host: smtp.gmail.com
    username: 
    password: 
    properties:
      smtp:
        auth: true
        socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory
          fallback: false
        starttls:
          enable: true
        ssl:
          enable: true

aws:
  access_key_id: AKIAIOKX4MZGGEATY2EA
  secret_access_key: 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

s3:
  bucket: curso-spring-ionic-2
  region: sa-east-1
  

jwt:
  secret: SequenciaDeCaracteresParaAssinarToken
  expiration: 86400000 # 1 dia
#  expiration: 60000 # 1 min

mail:
  default:
    sender: fabio.hb@gmail.com
    recipient: fabio.hb@gmail.com
  