spring:
  datasource:
    url: jdbc:mysql://localhost:3306/curso_spring
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
